# url: https://redseatechies.github.io
# baseurl: /

# Site settings
title: RED SEA TECHIES
email: andrew.yip@kaust.edu.sa
description: "code for the better > together"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffff00
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Andrew Yip
  pic: andrew
  position: KBus
  social:
    - title: github
      url: https://github.com/yipcma

# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (twitter, facebook, stack-overflow, bitbucket, github, google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/redseatechies
  - title: github
    url: https://github.com/redseatechies

# Postal address (add as many lines as necessary)
address:
  - line: KAUST, Thuwal, KSA

# Build settings
markdown: kramdown
permalink: pretty
